name: Build and deploy .deb file

on:
  push:
    branches:
      - main
      - v5.3.9
  pull_request:
    branches:
      - v5.3.9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install make debhelper
      - name: Build C project
        run: make
      - name: Create .deb file
        run: dpkg-buildpackage -rfakeroot -us -uc
      - name: Upload .deb file
        uses: actions/upload-artifact@v2
        with:
          name: my-project.deb
          path: ./debian/artifacts/my-project_0.1.0_amd64.deb


          
          




