name: Build and Deploy Deb Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          yarn install
      - name: Build the C project
        run: |
          yarn build
      - name: Create the .deb file
        run: |
          dpkg-buildpackage -b
      - name: Upload the .deb file
        uses: actions/upload-artifact@v3
        with:
          name: my-deb-package
          path: dist/*.deb



