on:
  push:
    branches:
      - main
      - v5.3.9
  pull_request:
    branches:
      - v5.3.9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install make debhelper dh-sequence-dkms
      - name: Build C project
        run: make
      - name: Create .deb file
        run: dpkg-buildpackage -b -rfakeroot -us -uc
      - name: ls
        run: ls
      - name: Upload .deb file
        uses: actions/upload-artifact@v2
        with:
          name: realtek-rtl8188eus-dkms.deb
          path: ../realtek-rtl8188eus-dkms_5.3.9~git20230101.f8ead57-0kali1_all.deb


          
          




